// Lav en string variabel med en længere tekst.
const str =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur blandit, elit vel dignissim varius, ligula mauris pulvinar ipsum, at tincidunt nisi purus vitae urna. Etiam sit amet nibh magna. Proin at eleifend sapien. Suspendisse a mauris est. Vivamus rutrum bibendum dictum. Phasellus sed condimentum purus. Phasellus posuere purus ac lorem fermentum egestas. Aenean quis molestie ipsum. Maecenas condimentum lacus quis dapibus commodo. Praesent efficitur lorem et mattis maximus.Phasellus tincidunt eu nulla at sagittis. Vivamus faucibus pellentesque nibh a finibus. Maecenas fringilla nibh at porta fringilla. Vestibulum vestibulum faucibus diam. Duis a mi tempor, blandit velit nec, mattis nibh. Curabitur sit amet consectetur lacus. Vivamus suscipit dolor mattis neque eleifend pretium non sed dolor. Nulla facilisi. In non placerat tellus, vel laoreet felis.Etiam in pharetra risus. Proin egestas dapibus nunc vel condimentum. Suspendisse elementum enim dignissim, suscipit lorem non, lacinia sem. Ut vitae euismod nunc, sed luctus sapien. Duis orci nibh, sodales et tellus et, suscipit iaculis justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus at placerat libero. Donec sit amet vestibulum ligula. Nulla facilisi. Duis nec tellus porta felis gravida tempus.In justo felis, auctor eget gravida sit amet, ultricies ac nunc. Phasellus tortor leo, sollicitudin maximus volutpat sed, pharetra et libero. Praesent dignissim magna sit amet purus finibus, ut consectetur dolor bibendum. Vestibulum augue tellus, luctus vel commodo vel, convallis id ligula. Duis ultrices id nulla sit amet faucibus. Aenean suscipit ligula sit amet nisi ullamcorper gravida. In tincidunt, metus sit amet pretium hendrerit, dolor est tempor massa, sit amet laoreet leo urna vel lacus. In venenatis maximus mi nec tempus.Aliquam venenatis massa sed sodales imperdiet. Phasellus a egestas odio, eu auctor dolor. Maecenas in risus consectetur, semper ligula eu, molestie nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque sed elit a augue suscipit dignissim at et diam. Sed vel enim in elit feugiat ultricies. Phasellus at aliquet enim. Vivamus porta volutpat nisi, sit amet faucibus neque pellentesque id. Sed consectetur blandit convallis. Donec placerat, neque eu sodales lobortis, nunc metus iaculis turpis, ac malesuada ipsum nibh a urna. Morbi scelerisque lectus at luctus euismod. Sed at lectus sit amet leo efficitur dictum id id libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam molestie urna eget lacus vulputate, in dapibus dui pulvinar.";

// Anvend dernæst et objekt som en map til at beregne antallet af de forskellige ord i teksten.
// Brug metoden split() til at opdele teksten i ord.

const map = {};
for (word of str.split(" ")) {
  map[word] = map[word] ? map[word] + 1 : 1;
}

console.log(Object.keys(map).length);
